### PR TITLE
give examples of where the robustness principal is better in routers

### PR DESCRIPTION
**Pull request by hardaker**
give examples of where the robustness principal is better in routers

### CODE REVIEW

**Review by martinthomson — COMMENTED** [review]
I need to think about this some more.  Maybe David has some ideas.

The obvious problem here is that this is in the wrong place.  I think that the point you are making might better fit in the next section (or even the previous one) as a standalone paragraph.

I would also reject the premise here to some extent: this is an excuse people put forth, not justification.  That is, if we aren't careful.  You have done a reasonable job of framing this as unavoidable rather than a good thing, but I want to see if we can be a bit more pointed here.  That equipment is not maintained is really a central problem we're trying to address, even if it isn't practical in the short term.

**Review by DavidSchinazi — CHANGES_REQUESTED** [review]
We have text in the Applicability section that explains how the guidance in this document doesn't apply when software updates aren't possible:

> Where implementations are not updated, there is no opportunity to apply the practices that this document recommends. In particular, some practices - such as those described in [Section 5.1](https://intarchboard.github.io/draft-protocol-maintenance/draft-iab-protocol-maintenance.html#intolerance) - only exist to support the development of protocol maintenance and evolution. Employing this guidance is therefore only applicable where there is the possibility of improving deployments through timely updates of their implementations.

I would propose adding the example of core Internet routers to that paragraph instead of here.

**Comment by DavidSchinazi** [comment]
In particular, I would not phrase it to say that the robustness principle is the best practice for routers - I would instead phrase it to say that this document doesn't apply. When you only have one option, that's not a best practice - it's just reality.

**Comment by DavidSchinazi** [comment]
Closing per email discussion

**Pull request closed without merging**
